#!/bin/bash

#  Copyright 2015-2016 bill-auger <https://github.com/bill-auger/av-caster/issues>
#
#  This file is part of the AvCaster program.
#
#  AvCaster is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 3
#  as published by the Free Software Foundation.
#
#  AvCaster is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with AvCaster.  If not, see <http://www.gnu.org/licenses/>.


export GST_DEBUG=2


cd Builds/Makefile && CONFIG=Debug make -j 2 && gdb
cd ../../
