#!/bin/bash

SCRIPTS_DIR=`pwd`


cd ../../
ln -s  $SCRIPTS_DIR/dbg               .
ln -s  $SCRIPTS_DIR/mk                .
ln -s  $SCRIPTS_DIR/mk-clean          .
ln -s  $SCRIPTS_DIR/mk-reset          .
ln -s  $SCRIPTS_DIR/cppcheck-filtered .
