/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "FfmpegStreamer.h"
#include "./Trace/TraceMain.h"


//==============================================================================
class FfmpegStreamerApplication : public JUCEApplication , public MultiTimer
{
public:

  FfmpegStreamerApplication() {}

  void initialise(const String& command_line) override
  {
    this->mainWindow          = new MainWindow(this) ;
    MainContent* main_content = (MainContent*)this->mainWindow->mainContent ;

    if (FfmpegStreamer::Initialize(main_content , command_line))
//     if (FfmpegStreamer::Initialize(this , main_content , command_line))
    {
      // start GUI update timers
      startTimer(CLIENT::GUI_TIMER_HI_ID , CLIENT::GUI_UPDATE_HI_IVL) ;
      startTimer(CLIENT::GUI_TIMER_LO_ID , CLIENT::GUI_UPDATE_LO_IVL) ;
    }
    else quit() ;
  }

  void anotherInstanceStarted (const String& commandLine) override
  {
    // When another instance of the app is launched while this one is running,
    // this method is invoked, and the commandLine parameter tells you what
    // the other instance's command-line arguments were.
  }

  void shutdown() override
  {
DBG("FfmpegStreamerApplication::shutdown()") ;

    FfmpegStreamer::Shutdown() ;

    this->mainWindow = nullptr ;

DEBUG_TRACE_SHUTDOWN
  }

  void         systemRequestedQuit()        override { DBG("FfmpegStreamerApplication::systemRequestedQuit()") ; this->quit() ; }
  const String getApplicationName()         override { return ProjectInfo::projectName ; }
  const String getApplicationVersion()      override { return ProjectInfo::versionString ; }
  bool         moreThanOneInstanceAllowed() override { return false ; }


  //==============================================================================
  /*
      This class implements the desktop window that contains an instance of
      our MainContent class.
  */
  class MainWindow : public DocumentWindow
  {
    friend class FfmpegStreamerApplication ;


  public:

    MainWindow(FfmpegStreamerApplication* app) : DocumentWindow(GUI::APP_NAME             ,
                                                                Colour(0xff202020)        ,
                                                                DocumentWindow::allButtons)
    {
      this->app = app ;

      // main content
      this->mainContent = new MainContent(this) ;
      this->mainContent->setComponentID(GUI::CONTENT_GUI_ID) ;
      setContentOwned(this->mainContent , true) ;

      // this main desktop window
#ifdef _MAC
      setTitleBarButtonsRequired(DocumentWindow::allButtons , true) ;
#endif // _MAC
      setTitleBarHeight(GUI::TITLEBAR_H) ;
//      setIcon(const Image &imageToUse) ;
      centreWithSize(getWidth() , getHeight()) ;
      setVisible(true) ;
    }

    ~MainWindow() { this->mainContent = nullptr ; }

    void closeButtonPressed() override { this->app->systemRequestedQuit() ; }


  private:

    FfmpegStreamerApplication* app ;
    ScopedPointer<MainContent> mainContent ;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(MainWindow)
  } ;


private:

  void timerCallback(int timer_id) override { FfmpegStreamer::HandleTimer(timer_id) ; }

  ScopedPointer<MainWindow> mainWindow ;
} ;

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION(FfmpegStreamerApplication)
